// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppDragArea: typeof import('./../components/AppDragArea.vue')['default']
    AppFileList: typeof import('./../components/AppFileList.vue')['default']
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppInput: typeof import('./../components/ui/AppInput.vue')['default']
    AppPreloader: typeof import('./../components/ui/AppPreloader.vue')['default']
    AppSettingRow: typeof import('./../components/AppSettingRow.vue')['default']
    AppToggle: typeof import('./../components/ui/AppToggle.vue')['default']
    SvgArrowCircleUp: typeof import('~icons/svg/arrow-circle-up')['default']
    SvgCog: typeof import('~icons/svg/cog')['default']
    SvgLogo: typeof import('~icons/svg/logo')['default']
    SvgTimes: typeof import('~icons/svg/times')['default']
  }
}

export {}
